"""add item health score columns

Revision ID: 5f474b8b27e1
Revises: 21516e9bb4a6
Create Date: 2026-06-14 18:12:46.432227
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5f474b8b27e1"
down_revision: str | None = "21516e9bb4a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("health_score", sa.SmallInteger(), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("health_class", sa.String(length=32), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("score_version", sa.String(length=32), nullable=True), schema="inventory"
    )
    op.add_column(
        "items",
        sa.Column("score_dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="inventory",
    )
    op.add_column(
        "items",
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "scored_at", schema="inventory")
    op.drop_column("items", "score_dimensions", schema="inventory")
    op.drop_column("items", "score_version", schema="inventory")
    op.drop_column("items", "health_class", schema="inventory")
    op.drop_column("items", "health_score", schema="inventory")
    # ### end Alembic commands ###
