"""add anomalies table

Revision ID: 92e695036b7b
Revises: a9a28d4e9181
Create Date: 2026-06-18 15:34:01.740487
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "92e695036b7b"
down_revision: str | None = "a9a28d4e9181"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ml.anomalies is tenant-scoped: enable the same default-deny RLS policy as
# every other tenant table (mirrors revision 7a266032b044). RLS is the safety
# net; the app sets app.current_tenant_id per request.
_FQ = "ml.anomalies"
_POLICY = "tenant_isolation"
_PREDICATE = "tenant_id = current_setting('app.current_tenant_id', true)::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomalies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("source_record_id", sa.String(length=128), nullable=True),
        sa.Column("score", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("detected_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenants.id"],
            name=op.f("fk_anomalies_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomalies")),
        sa.UniqueConstraint("tenant_id", "type", "target_id", name="uq_anomalies_target"),
        schema="ml",
    )
    op.create_index(
        op.f("ix_ml_anomalies_tenant_id"), "anomalies", ["tenant_id"], unique=False, schema="ml"
    )
    # ### end Alembic commands ###
    op.execute(f"ALTER TABLE {_FQ} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_FQ} FORCE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY {_POLICY} ON {_FQ} USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP POLICY IF EXISTS {_POLICY} ON {_FQ}")
    op.drop_index(op.f("ix_ml_anomalies_tenant_id"), table_name="anomalies", schema="ml")
    op.drop_table("anomalies", schema="ml")
    # ### end Alembic commands ###
