"""cv4 risk columns and supplier reliability

Revision ID: a7a6b9eaa367
Revises: c72ee81a0e02
Create Date: 2026-06-19 11:41:23.146059
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a7a6b9eaa367"
down_revision: str | None = "c72ee81a0e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("criticality", sa.SmallInteger(), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("primary_supplier_id", sa.UUID(), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("risk_score", sa.SmallInteger(), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("risk_class", sa.String(length=32), nullable=True), schema="inventory"
    )
    op.add_column(
        "items", sa.Column("risk_version", sa.String(length=32), nullable=True), schema="inventory"
    )
    op.add_column(
        "items",
        sa.Column("risk_breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema="inventory",
    )
    op.add_column(
        "items",
        sa.Column(
            "is_critical_spare", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
        schema="inventory",
    )
    op.add_column(
        "items", sa.Column("critical_reason", sa.Text(), nullable=True), schema="inventory"
    )
    op.create_foreign_key(
        op.f("fk_items_primary_supplier_id_suppliers"),
        "items",
        "suppliers",
        ["primary_supplier_id"],
        ["id"],
        source_schema="inventory",
        referent_schema="inventory",
        ondelete="SET NULL",
    )
    op.add_column(
        "suppliers",
        sa.Column("on_time_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        schema="inventory",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("suppliers", "on_time_rate", schema="inventory")
    op.drop_constraint(
        op.f("fk_items_primary_supplier_id_suppliers"),
        "items",
        schema="inventory",
        type_="foreignkey",
    )
    op.drop_column("items", "critical_reason", schema="inventory")
    op.drop_column("items", "is_critical_spare", schema="inventory")
    op.drop_column("items", "risk_breakdown", schema="inventory")
    op.drop_column("items", "risk_version", schema="inventory")
    op.drop_column("items", "risk_class", schema="inventory")
    op.drop_column("items", "risk_score", schema="inventory")
    op.drop_column("items", "primary_supplier_id", schema="inventory")
    op.drop_column("items", "criticality", schema="inventory")
    # ### end Alembic commands ###
