"""add duplicate candidates table

Revision ID: a9a28d4e9181
Revises: 5f474b8b27e1
Create Date: 2026-06-18 14:54:56.996632
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a9a28d4e9181"
down_revision: str | None = "5f474b8b27e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ml.duplicate_candidates is tenant-scoped: enable the same default-deny RLS
# policy as every other tenant table (mirrors revision 7a266032b044). RLS is
# the safety net; the app sets app.current_tenant_id per request.
_FQ = "ml.duplicate_candidates"
_POLICY = "tenant_isolation"
_PREDICATE = "tenant_id = current_setting('app.current_tenant_id', true)::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("item_a_id", sa.UUID(), nullable=False),
        sa.Column("item_b_id", sa.UUID(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_by", sa.UUID(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_a_id < item_b_id", name=op.f("ck_duplicate_candidates_canonical_pair_order")
        ),
        sa.ForeignKeyConstraint(
            ["item_a_id"],
            ["inventory.items.id"],
            name=op.f("fk_duplicate_candidates_item_a_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_b_id"],
            ["inventory.items.id"],
            name=op.f("fk_duplicate_candidates_item_b_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenants.id"],
            name=op.f("fk_duplicate_candidates_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_candidates")),
        sa.UniqueConstraint(
            "tenant_id", "item_a_id", "item_b_id", name="uq_duplicate_candidates_pair"
        ),
        schema="ml",
    )
    op.create_index(
        op.f("ix_ml_duplicate_candidates_tenant_id"),
        "duplicate_candidates",
        ["tenant_id"],
        unique=False,
        schema="ml",
    )
    # ### end Alembic commands ###
    op.execute(f"ALTER TABLE {_FQ} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {_FQ} FORCE ROW LEVEL SECURITY")
    op.execute(f"CREATE POLICY {_POLICY} ON {_FQ} USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"DROP POLICY IF EXISTS {_POLICY} ON {_FQ}")
    op.drop_index(
        op.f("ix_ml_duplicate_candidates_tenant_id"), table_name="duplicate_candidates", schema="ml"
    )
    op.drop_table("duplicate_candidates", schema="ml")
    # ### end Alembic commands ###
