"""cv3 lead time and recommendation feedback

Revision ID: c72ee81a0e02
Revises: 92e695036b7b
Create Date: 2026-06-18 19:21:02.649668
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c72ee81a0e02"
down_revision: str | None = "92e695036b7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Both new ml tables are tenant-scoped: enable the same default-deny RLS policy
# as every other tenant table (mirrors revision 7a266032b044).
_RLS_TABLES = ("ml.recommendation_feedback", "ml.regime_signals")
_POLICY = "tenant_isolation"
_PREDICATE = "tenant_id = current_setting('app.current_tenant_id', true)::uuid"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_feedback",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=32), nullable=True),
        sa.Column("reason_note", sa.Text(), nullable=True),
        sa.Column("adjusted_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["ml.recommendations.id"],
            name=op.f("fk_recommendation_feedback_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenants.id"],
            name=op.f("fk_recommendation_feedback_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_feedback")),
        schema="ml",
    )
    op.create_index(
        op.f("ix_ml_recommendation_feedback_tenant_id"),
        "recommendation_feedback",
        ["tenant_id"],
        unique=False,
        schema="ml",
    )
    op.create_table(
        "regime_signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("dimension", sa.String(length=32), nullable=False),
        sa.Column("override_count", sa.Integer(), nullable=False),
        sa.Column("last_reason_note", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["inventory.items.id"],
            name=op.f("fk_regime_signals_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["core.tenants.id"],
            name=op.f("fk_regime_signals_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regime_signals")),
        sa.UniqueConstraint("tenant_id", "item_id", "dimension", name="uq_regime_signals_axis"),
        schema="ml",
    )
    op.create_index(
        op.f("ix_ml_regime_signals_tenant_id"),
        "regime_signals",
        ["tenant_id"],
        unique=False,
        schema="ml",
    )
    op.add_column(
        "items", sa.Column("lead_time_days", sa.SmallInteger(), nullable=True), schema="inventory"
    )
    # ### end Alembic commands ###
    for fq in _RLS_TABLES:
        op.execute(f"ALTER TABLE {fq} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {fq} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {_POLICY} ON {fq} USING ({_PREDICATE}) WITH CHECK ({_PREDICATE})"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for fq in _RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {_POLICY} ON {fq}")
    op.drop_column("items", "lead_time_days", schema="inventory")
    op.drop_index(op.f("ix_ml_regime_signals_tenant_id"), table_name="regime_signals", schema="ml")
    op.drop_table("regime_signals", schema="ml")
    op.drop_index(
        op.f("ix_ml_recommendation_feedback_tenant_id"),
        table_name="recommendation_feedback",
        schema="ml",
    )
    op.drop_table("recommendation_feedback", schema="ml")
    # ### end Alembic commands ###
